In [2]:
import pandas as pd
import sklearn
from sklearn.linear_model import LinearRegression
import numpy as np
from pandas_summary import DataFrameSummary
import pandas_profiling as pp
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegressionCV
from sklearn import preprocessing
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
import random
%matplotlib inline
from IPython.core.debugger import set_trace #!!TODO: remove this

In [26]:
train_set_df = pd.read_csv("mercari-price-suggestion-challenge/train.tsv", sep='\t' )

In [31]:
train_set_df.iloc[0:200, :].to_csv("mercari-price-suggestion-challenge/train_small.csv", sep=',' )

In [34]:
len(train_set_df.iloc[0:200, :]['name'].unique())

200

In [17]:
len(train_set_df.category_name.unique())

1288

In [18]:
train_set_df.category_name.unique()

array(['Men/Tops/T-shirts',
       'Electronics/Computers & Tablets/Components & Parts',
       'Women/Tops & Blouses/Blouse', ..., 'Handmade/Jewelry/Clothing',
       'Vintage & Collectibles/Supplies/Ephemera',
       'Handmade/Pets/Blanket'], dtype=object)

In [102]:
import numpy as np
# import np.random
m = np.random.randint(0, 100, size=(5, 2, 3))
mm = np.random.randint(0, 100, size=(5, 2, 3))

In [104]:
m, mm

(array([[[45, 27, 42],
         [ 7, 36, 19]],
 
        [[ 3, 11, 46],
         [40, 60,  6]],
 
        [[34, 31, 42],
         [38, 27, 39]],
 
        [[73, 57,  3],
         [62, 67,  1]],
 
        [[15, 98,  6],
         [66, 88, 99]]]),
 array([[[ 3, 99, 56],
         [72, 46, 70]],
 
        [[68, 25,  5],
         [91, 72, 34]],
 
        [[12, 53,  2],
         [14,  7, 69]],
 
        [[89, 47, 13],
         [30,  4, 17]],
 
        [[47, 86, 28],
         [63, 80, 18]]]))

In [107]:
m*mm


array([[[ 135, 2673, 2352],
        [ 504, 1656, 1330]],

       [[ 204,  275,  230],
        [3640, 4320,  204]],

       [[ 408, 1643,   84],
        [ 532,  189, 2691]],

       [[6497, 2679,   39],
        [1860,  268,   17]],

       [[ 705, 8428,  168],
        [4158, 7040, 1782]]])

In [109]:
np.max(m*mm, axis=0)

array([[6497, 8428, 2352],
       [4158, 7040, 2691]])

In [112]:
A = np.array([[1,2,3], [4,5,6], [7,8,9], [1,1,1],[2,2,2]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 1, 1],
       [2, 2, 2]])

In [113]:
m

array([[[45, 27, 42],
        [ 7, 36, 19]],

       [[ 3, 11, 46],
        [40, 60,  6]],

       [[34, 31, 42],
        [38, 27, 39]],

       [[73, 57,  3],
        [62, 67,  1]],

       [[15, 98,  6],
        [66, 88, 99]]])

In [116]:
m[:,0,1] = np.array[A[:,2], A[:,1], A[:0], A[:1]]
m

array([[[45,  3, 42],
        [ 7, 36, 19]],

       [[ 3,  6, 46],
        [40, 60,  6]],

       [[34,  9, 42],
        [38, 27, 39]],

       [[73,  1,  3],
        [62, 67,  1]],

       [[15,  2,  6],
        [66, 88, 99]]])

In [120]:
np.array([A[:,2], A[:,1], A[:,0], A[:1]])


array([array([3, 6, 9, 1, 2]), array([2, 5, 8, 1, 2]),
       array([1, 4, 7, 1, 2]), array([[1, 2, 3]])], dtype=object)

In [121]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 1, 1],
       [2, 2, 2]])

In [123]:
B = np.copy(A)
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 1, 1],
       [2, 2, 2]])

In [124]:
B[0,0] = 7
B

array([[7, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 1, 1],
       [2, 2, 2]])

In [125]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 1, 1],
       [2, 2, 2]])

In [126]:
C = A

In [127]:
C[0,0] = 9
A

array([[9, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 1, 1],
       [2, 2, 2]])

In [70]:
kernel


array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [72]:
np.arange(5,0,-1)/100

array([0.05, 0.04, 0.03, 0.02, 0.01])

In [85]:
kernel = np.arange(5,0,-1)/100
temp = kernel[:, np.newaxis].dot(np.arange(1,6)[np.newaxis, :])
print(temp)
temp.sum(axis=0)

[[0.05 0.1  0.15 0.2  0.25]
 [0.04 0.08 0.12 0.16 0.2 ]
 [0.03 0.06 0.09 0.12 0.15]
 [0.02 0.04 0.06 0.08 0.1 ]
 [0.01 0.02 0.03 0.04 0.05]]


array([0.15, 0.3 , 0.45, 0.6 , 0.75])

In [78]:
kernel[:, np.newaxis]

array([[0.05],
       [0.04],
       [0.03],
       [0.02],
       [0.01]])

In [80]:
np.arange(1,6)[np.newaxis, :].shape

(1, 5)

In [128]:
A

array([[9, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 1, 1],
       [2, 2, 2]])

In [130]:
A[:,:,None].shape

(5, 3, 1)

In [89]:
b= [a]*3

[array([[1],
        [2],
        [3]]),
 array([[1],
        [2],
        [3]]),
 array([[1],
        [2],
        [3]])]

In [133]:
m = np.random.uniform( size=(5, 2))
m

array([[0.08210182, 0.81018534],
       [0.50012392, 0.65938366],
       [0.91461112, 0.35879139],
       [0.82010446, 0.37834646],
       [0.34617954, 0.78813178]])

In [135]:
m[m < 0.5]

array([0.08210182, 0.35879139, 0.37834646, 0.34617954])

In [138]:
tmp = np.array([1,2,3,4,5])

In [142]:
np.maximum(tmp,3)

array([3, 3, 3, 4, 5])